version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
permissions:
   - object: /home/ubuntu/build
     pattern: "**"
    
hooks:
  BeforeInstall:
    - location: dependencies.sh
      timeout: 180
      runas: root
   
  AfterInstall:
    - location: start.sh
      timeout: 180
      runas: root
