version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist/angular-ui/scripts
permissions:
  - object: /home/ubuntu/dist/angular-ui/scripts
    pattern: "**"
    
hooks:
  BeforeInstall:
    - location: angular-ui/scripts/dependencies.sh
   
  AfterInstall:
    - location: angular-ui/scripts/start.sh
      timeout: 180
