version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist/angular-ui/scripts
permissions:
  - object: /home/ubuntu/dist/angular-ui/scripts
    pattern: "**"

hooks:
  BeforeInstall:
    - location: scripts/dependencies.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: root
